local = False
"""
Django settings for moodibuddy project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'li)!esp-2-xi@t((d!m9*=p_y(qhqkw5(9t%*(cu&n3i^q_)t3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '54.180.93.247',
    'ec2-54-180-93-247.ap-northeast-2.compute.amazonaws.com',
]

INTERNAL_IPS = ('127.0.0.1', 'ec2-54-180-93-247.ap-northeast-2.compute.amazonaws.com')
# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user.apps.UserProfileConfig',
    'diary.apps.DiaryConfig',
    'stats.apps.StatsConfig',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

ROOT_URLCONF = 'moodibuddy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'moodibuddy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

if local: #LOCAL TEST ENV
    DATABASES = {
        'default': {
            'ENGINE':'django.db.backends.postgresql',
            'HOST': '127.0.0.1', 'localhost'
            'PORT': 5432,
            'NAME': 'moodibuddy',
            'USER': 'moodibuddy_dev',
            'PASSWORD': 'password',
        }
    }
else :
    #DEPLOYED ENV
    DATABASES = {
        'default': {
            'ENGINE':'django.db.backends.postgresql',
            'HOST': 'moodibuddy-db.cwybyntak1ph.ap-northeast-2.rds.amazonaws.com',
            'PORT': 5432,
            'NAME': 'moodibuddy_alpha',
            'USER': 'moodibuddy_dev',
            'PASSWORD': 'password',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

###############################################################
###################### EMAIL VERIFICATION #####################
###############################################################

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'moodibuddy@gmail.com'
EMAIL_HOST_PASSWORD = '210109moodybuddy'
SERVER_EMAIL = 'moodibuddy@gmail.com'
DEFAULT_FROM_MAIL = 'moodibuddy_dev'