# Generated by Django 3.1 on 2021-02-12 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_index=True, max_length=20)),
                ('emotion', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], db_index=True, max_length=5)),
                ('fieldA', models.CharField(db_index=True, max_length=500)),
                ('fieldB', models.CharField(db_index=True, max_length=500)),
                ('fieldC', models.CharField(blank=True, db_index=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_diary', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
